config/routes.rb
Rails.application.routes.draw do
  root to: "spree/home#index"
  mount Spree::Core::Engine, :at => '/'
end

Spree::Core::Engine.routes.draw do
  get '/about', to: 'pages#about', as: :about
  get '/services', to: 'pages#services', as: :services
  get '/services/theme-reception-decoration', to: 'pages#services_theme_decor', as: :services_theme_decor
  get '/services/theme-reception-decoration/nautical-theme', to: 'pages#services_theme_nautical', as: :services_theme_nautical
  get '/services/theme-reception-decoration/summer-theme', to: 'pages#services_theme_summer', as: :services_theme_summer
  get '/services/theme-reception-decoration/romance-theme', to: 'pages#services_theme_romance', as: :services_theme_romance
  get '/services/theme-reception-decoration/glamor-theme', to: 'pages#services_theme_glamor', as: :services_theme_glamor
  get '/services/theme-reception-decoration/asian-theme', to: 'pages#services_theme_asian', as: :services_theme_asian
  get '/services/customised-stationaries', to: 'pages#services_customised_stationaries', as: :services_customised_stationaries
  get '/services/wedding-planning', to: 'pages#services_wedding_planning', as: :services_wedding_planning
  get '/privacy', to: 'pages#privacy', as: :privacy
  get '/delivery', to: 'pages#delivery', as: :delivery
  get '/terms', to: 'pages#terms', as: :terms
  get '/service-order', to: 'service_order#new', as: :service_order
  post '/service-order', to: 'service_order#submit'
  get '/contact', to: 'contact#new', as: :contact
  post '/contact', to: 'contact#submit'
  get 'orders/:order_id/print', to: 'orders#print', as: :print_order

  # Subscriptions
  resources :subscriptions, only: [:create, :update, :destroy]
  get 'reports/subscriptions', to: 'admin/reports#subscriptions', as: :subscriptions_admin_reports
  get 'reports/subscriptions/csv', to: 'admin/reports#subscriptions_csv', as: :subscriptions_admin_reports_csv
end

app/views/shared/_back.html.erb
<div id="back">
  <a href="javascript:history.back()" class="ss-button">Back</a>
</div>

app/views/shared/_head.html.erb
<!-- Meta Tags -->
<meta charset="UTF-8"/>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta name="description" content="OneMoment Singapore Online Wedding Shop"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<%== meta_data_tags %>
<%= canonical_tag(current_store.url) %>
<!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"/><![endif]-->

<!-- Title -->
<title>OneMoment | Online Wedding Services and Products</title>

<!-- Favicon -->
<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon"/>
<link rel="icon" href="images/favicon.ico" type="image/x-icon"/>

<!--[if lte IE 9]
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,400italic,500italic,300italic' rel='stylesheet' type='text/css'>


<%= stylesheet_link_tag 'application', media: 'all' %>
<%= csrf_meta_tags %>

<%= yield :head %>

app/views/shared/_main_container.html.erb
<div id="main-container" class="main-container ss-ajaxable" data-animation-type="fade-from-bottom" data-animation-speed="0.4" data-animation-out-speed="0.6">
  <section class="inner-wrapper">
    <%= render 'spree/shared/messages' %>
    <%= yield %>
  </section>
</div>

app/views/shared/_mobile_header.html.erb
<div class="mobile-header">
  <a class="ss-mobile-menu-button" href="#menu"><span class="icon-menu6"></span></a>
  <a class="ss-mobile-menu sidebar-toggle-button ss-no-ajax" href="#"><span class="icon-menu"></span></a>
  <div class="logo">
      <a href="#" title="OneMoment">
        <%= image_tag 'logo.png', alt: 'OneMoment logo' %>
      </a>
      <span class="logo-slogan">Love And Harmony</span>
  </div>
</div>

app/views/shared/_nav.html.erb
<header class="main-header">
  <div id="main-header-scrollbar" class="main-header-scrollbar">
    <div class="handle">
      <div class="mousearea"></div>
    </div>
  </div>

  <div id="main-header-frame" class="main-header-frame" style="overflow: hidden;">

    <div class="header-wrapper">    

      <div class="cart-menu">
        <%= render 'shared/nav_login' %>
        <%= render 'shared/nav_cart' %>
      </div>

      <div class="logo">
        <a href="<%= root_path %>" title="OneMoment">
          <%= image_tag 'logo.png', alt: 'OneMoment logo' %>
          <div class="logo-separator"></div>
          <span class="logo-slogan">Create everlasting good memories</span>
        </a>
      </div>
      
      <div class="mobile-close-button">
        <a class="ss-no-ajax" href="#">
          <span class="icon-close2" aria-hidden="true"></span>
        </a>
      </div>

      <div class="header-menu">
        <nav class="main-navigation-container">
          <ul class="main-navigation">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'About us', about_path %></li>
            <li class="menu-item-has-children"><a href="#">Products</a>
              <ul class="sub-menu">
                <%= taxons_tree(product_category_taxon, @taxon, 1) if product_category_taxon %>
              </ul>
            </li>
            <li class="menu-item-has-children"><%= link_to 'Services (Available Soon)', services_path %>
              <ul class="sub-menu">
                <li><%= link_to 'Reception Theme Decoration', services_theme_decor_path %></li>
                <li><%= link_to 'Customise Stationaries for Events', services_customised_stationaries_path %></li>
                <li>
                  <%= link_to services_path do %>
                    Wedding Planning
                  <% end %>
                </li>
              </ul>
            </li>
            <li ><%= link_to 'Contact', contact_path %></li>
            <li class="menu-item-has-children"><a href="#">Information</a>
              <ul class="sub-menu">
                <li><%= link_to 'Privacy policy', privacy_path %></li>
                <li><%= link_to 'Terms & Conditions', terms_path %></li>
                <li><%= link_to 'Delivery', delivery_path %></li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>

      <div class="newsletter">
        <p>Sign up for newsletter</p>
        <%= form_for subscription, method: 'post' do |f| %>
          <%= f.text_field :email, id: "newsletter-input", placeholder: "email address..." %>
          <%= f.hidden_field :active, value: true %>
        <% end %>
      </div>

      <div class="social-media">
        <a href="https://www.facebook.com/profile.php?id=100007613178855"><span class="social-icon fb-icon"></span></a>
        <a href="https://onemomentsg.wordpress.com"><span class="social-icon wp-icon"></span></a>
        <a href="http://instagram.com/onemomentsg"><span class="social-icon ig-icon"></span></a>
      </div>

      <div class="copyright">Copyright © 2014. All Rights Reserved.</div>
    </div>

  </div><!--iframe-->
</header>

app/views/shared/_nav_cart.html.erb
<span id="link-to-cart">
  <%= link_to_cart %>
</span>
<script>Spree.fetch_cart()</script>

app/views/shared/_nav_login.html.erb
<%= link_to "Track Order", 'http://www.ninjavan.sg/' %>
<% if spree_current_user %>
  <%= link_to 'Account', spree.account_path %>
  <%= link_to Spree.t(:logout), spree.logout_path %>
<% else %>
  <%= link_to Spree.t(:login), spree.login_path %>
<% end %>

app/views/shared/_preloader.html.erb
<div class="ss-preloader">
  <div class="ss-preloader-spin"></div>
</div>

app/views/shared/_product_add_to_cart.html.erb
<% if product.variants_and_option_values(current_currency).any? %>
  <a href="<%= url %>"><span class="icon-cart" aria-hidden="true"></span> Add to Cart</a>
<% else %>
  <%= form_for :order, url: populate_orders_path, html: { id: "add-to-cart-#{product.id}" } do |f| %>
    <%= hidden_field_tag "variant_id", product.master.id %>
    <%= hidden_field_tag :quantity, 1 %>
    <%= button_tag class: "product-add-to-cart" do %>
      <span class="icon-cart" aria-hidden="true"></span> Add to Cart
    <% end %>
  <% end %>
<% end %>

app/views/shared/_wrapper.html.erb
<div id="wrapper" class="wrapper">
  <%= render 'shared/mobile_header' %>
  <%= render 'shared/main_container.html.erb' %>
</div>